name: windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        architecture: [Win32, x64]
    steps:
      - uses: actions/checkout@v3
      - name: Configure
        run: cmake -B build -G "Visual Studio 17 2022" -A ${{ matrix.architecture }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel 10
      - name: Test
        working-directory: build
        run: ctest -C ${{ matrix.build_type }}